gs_homepage:
    path:     /home
    defaults: { _controller: GsBundle:Default:index }

calculate:
    path:     /calculate
    defaults: { _controller: GsBundle:Default:calculate }

additiontrou:
    path:     /additionpartrou
    defaults: { _controller: GsBundle:Default:additionParTrou }

soustraction:
    path:     /soustraction
    defaults: { _controller: GsBundle:Default:soustraction }

comparertrois:
    path:     /comparertrois
    defaults: { _controller: GsBundle:Default:comparerpartrois }

moinsplus:
    path:     /moinsplus
    defaults: { _controller: GsBundle:Default:moinsplus }


compterdeux:
    path:     /compterdeux
    defaults: { _controller: GsBundle:Default:compterdeux }

jourssemaines:
    path:     /jourssemaines
    defaults: { _controller: GsBundle:Default:jourssemaines }

moisannees:
    path:     /moisannees
    defaults: { _controller: GsBundle:Default:moisannees }

liretemperature:
    path:     /liretemperature
    defaults: { _controller: GsBundle:Default:liretemperature }

comparerlongueurs:
    path:     /comparerlongueurs
    defaults: { _controller: GsBundle:Default:comparerlongueurs }

mesurerlongueurs:
    path:     /mesurerlongueurs
    defaults: { _controller: GsBundle:Default:mesurerlongueurs }

recsolides:
    path:     /recsolides
    defaults: { _controller: GsBundle:Default:recsolides }

planes:
    path:     /planes
    defaults: { _controller: GsBundle:Default:planes }

