<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM4ga6uc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM4ga6uc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerM4ga6uc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerM4ga6uc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerM4ga6uc\appProdProjectContainer([
    'container.build_hash' => 'M4ga6uc',
    'container.build_id' => 'eecdd7de',
    'container.build_time' => 1595959737,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM4ga6uc');
